include file("/app/upstream.conf")
canton.participants.app-provider.parameters.initial-protocol-version = 35
canton.participants.app-user.parameters.initial-protocol-version = 35
canton.participants.sv.parameters.initial-protocol-version = 35
