spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_APPLICATION_ISSUER_URL}
          jwk-set-uri: ${AUTH_APPLICATION_JWK_SET_URL}
          audiences: backend
      client:
        registration:
          ledger:
            client-id: ${AUTH_APP_PROVIDER_BACKEND_CLIENT_ID}
            client-secret: ${AUTH_APP_PROVIDER_BACKEND_SECRET}
            authorization-grant-type: client_credentials
            provider: participant
        provider:
          participant:
            token-uri: ${AUTH_APP_PROVIDER_TOKEN_URL}
